### ISSUE TITLE
Improve abSlotOverrideList operation

### ISSUE THREAD

**Issue by GAntono** [GAntono/SerialStrip#15]
I want to have the argument abSlotOverrideList default to a False Bool[] array 33 items long, unless the modder gives another array. It seems I cannot do:
Function PrepareForStripping(Actor akActorRef, String asExceptionListKey = "", Bool[] abSlotOverrideList = None).

Is there any elegant way of doing this? Currently I am passing a default array with all 33 false items.

**Comment by heromaster** [comment]
Nope you can't pass an optional array argument to the compiler.

What you can do would be create a helper function like

Function UseOverrideList(Bool[] abSlotOverrideList) and save that somehow to make the stripping function aware that it should use the abSlotOverrideList instead of the default one.

**Comment by GAntono** [comment]
Closed in 91166a6b4114d26b3fa32202f6fecc639bd63f3b
